#!/bin/sh

FWUPDATE_STATUS_FILE=${FWUPDATE_STATUS_FILE:-/run/fwupdate/status.json}
FWUPDATE_LOG_FILE=${FWUPDATE_LOG_FILE:-/run/fwupdate/update.log}
FWUPDATE_LOCK_DIR=${FWUPDATE_LOCK_DIR:-/run/fwupdate.lock}
FWUPDATE_WORK_BASE=${FWUPDATE_WORK_BASE:-/tmp}
FWUPDATE_PLATFORM=${FWUPDATE_PLATFORM:-ms42p}
FWUPDATE_ROOTFS_NAME=${FWUPDATE_ROOTFS_NAME:-}
FWUPDATE_OVERLAY_NAME=${FWUPDATE_OVERLAY_NAME:-}
FWUPDATE_ROOTFS_SIZE=$((0x800000))
FWUPDATE_OVERLAY_SIZE=$((0x500000))
FWUPDATE_FULL_IMAGE_SIZE=$((0x1000000))
FWUPDATE_ROOTFS_OFFSET=$((0x300000))
FWUPDATE_OVERLAY_OFFSET=$((0xb00000))
FWUPDATE_KERNEL_OFFSET=$((0x40000))
FWUPDATE_SOURCES_FILE=${FWUPDATE_SOURCES_FILE:-/etc/fwupdate/sources.conf}
FWUPDATE_PRESERVE_FILE=${FWUPDATE_PRESERVE_FILE:-/etc/fwupdate/preserve.list}

mkdir -p /run/fwupdate 2>/dev/null || true

ts() { date +%s 2>/dev/null || echo 0; }

json_escape() {
    # Status fields generated by these scripts are single-line strings.
    printf '%s' "$1" | sed \
        -e 's/\\/\\\\/g' \
        -e 's/"/\\"/g'
}

status_write() {
    state=$1
    stage=$2
    progress=$3
    message=$4
    source=${5:-${FWUPDATE_SOURCE:-}}
    firmware=${6:-${FWUPDATE_FIRMWARE:-}}
    tmp="${FWUPDATE_STATUS_FILE}.tmp.$$"
    mkdir -p "$(dirname "$FWUPDATE_STATUS_FILE")" 2>/dev/null || true
    {
        printf '{"state":"%s","stage":"%s","progress":%s,"timestamp":%s,' \
            "$(json_escape "$state")" "$(json_escape "$stage")" "$progress" "$(ts)"
        printf '"message":"%s","source":"%s","firmware":"%s"}\n' \
            "$(json_escape "$message")" "$(json_escape "$source")" \
            "$(json_escape "$firmware")"
    } > "$tmp" && mv -f "$tmp" "$FWUPDATE_STATUS_FILE"
    printf '%s|%s|%s|%s|%s\n' "$(ts)" "$state" "$stage" "$progress" "$message" \
        >> "$FWUPDATE_LOG_FILE" 2>/dev/null || true
    printf 'FWUPDATE|%s|%s|%s|%s\n' "$state" "$stage" "$progress" "$message"
}

fw_die() {
    msg=$1
    status_write error error 100 "$msg"
    printf 'error: %s\n' "$msg" >&2
    exit 1
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || fw_die "required command is missing: $1"
}

file_size() {
    wc -c < "$1" | awk '{print $1}'
}

read_magic() {
    file=$1
    offset=$2
    count=$3
    dd if="$file" bs=1 skip="$offset" count="$count" 2>/dev/null
}

read_hex() {
    file=$1
    offset=$2
    count=$3
    read_magic "$file" "$offset" "$count" | hexdump -v -e '1/1 "%02x"'
}

mtd_lookup() {
    name=$1
    awk -v n="\"$name\"" '
        $4 == n {
            dev=$1; sub(/:$/, "", dev);
            print dev, $2, $3;
            exit
        }
    ' /proc/mtd
}

mtd_lookup_first() {
    for candidate in "$@"; do
        [ -n "$candidate" ] || continue
        entry=$(mtd_lookup "$candidate")
        if [ -n "$entry" ]; then
            printf '%s\n' "$entry"
            return 0
        fi
    done
    return 1
}

mtd_lookup_fstab_overlay() {
    dev=$(awk '$2 == "/overlay" && $1 ~ /^\/dev\/mtdblock[0-9]+$/ {print $1; exit}' /etc/fstab 2>/dev/null)
    [ -n "$dev" ] || return 1
    num=${dev#/dev/mtdblock}
    awk -v d="mtd${num}:" '$1 == d {dev=$1; sub(/:$/, "", dev); print dev, $2, $3; exit}' /proc/mtd
}

check_mtd_layout() {
    if [ -n "$FWUPDATE_ROOTFS_NAME" ]; then
        root_entry=$(mtd_lookup "$FWUPDATE_ROOTFS_NAME")
    else
        root_entry=$(mtd_lookup_first squashfs rootfs || true)
    fi
    if [ -n "$FWUPDATE_OVERLAY_NAME" ]; then
        overlay_entry=$(mtd_lookup "$FWUPDATE_OVERLAY_NAME")
    else
        overlay_entry=$(mtd_lookup_first jffs2 config overlay storage || true)
        [ -n "$overlay_entry" ] || overlay_entry=$(mtd_lookup_fstab_overlay || true)
    fi
    [ -n "$root_entry" ] || fw_die "8 MiB SquashFS MTD partition was not found"
    [ -n "$overlay_entry" ] || fw_die "5 MiB JFFS2/config MTD partition was not found"

    set -- $root_entry
    ROOT_MTD=$1
    ROOT_MTD_SIZE=$((0x$2))
    ROOT_MTD_LABEL=$(printf '%s' "${4:-}" | tr -d '"')
    set -- $overlay_entry
    OVERLAY_MTD=$1
    OVERLAY_MTD_SIZE=$((0x$2))
    OVERLAY_MTD_LABEL=$(printf '%s' "${4:-}" | tr -d '"')

    [ "$ROOT_MTD_SIZE" -eq "$FWUPDATE_ROOTFS_SIZE" ] || \
        fw_die "unexpected SquashFS partition size: $ROOT_MTD_SIZE"
    [ "$OVERLAY_MTD_SIZE" -eq "$FWUPDATE_OVERLAY_SIZE" ] || \
        fw_die "unexpected JFFS2/config partition size: $OVERLAY_MTD_SIZE"
    [ -c "/dev/$ROOT_MTD" ] || fw_die "/dev/$ROOT_MTD is missing"
    [ -c "/dev/$OVERLAY_MTD" ] || fw_die "/dev/$OVERLAY_MTD is missing"
    export ROOT_MTD OVERLAY_MTD ROOT_MTD_SIZE OVERLAY_MTD_SIZE ROOT_MTD_LABEL OVERLAY_MTD_LABEL
}

check_board() {
    model=""
    if command -v board_data >/dev/null 2>&1; then
        model=$(board_data model 2>/dev/null | tr -d '\r\n' || true)
    fi
    [ -n "$model" ] || model=$(cat /etc/boardinfo 2>/dev/null | tr -d '\r\n' || true)
    case "$model" in
        *MS42P*|*MS42*) return 0 ;;
        "") fw_die "could not identify the board as MS42/MS42P" ;;
        *) fw_die "unsupported board model: $model" ;;
    esac
}


check_work_base_ram() {
    case "$FWUPDATE_WORK_BASE" in
        /tmp|/tmp/*) mount_at=/tmp ;;
        /run|/run/*) mount_at=/run ;;
        *) fw_die "firmware work directory must be under /tmp or /run" ;;
    esac
    fs_type=$(awk -v m="$mount_at" '$2 == m {print $3; exit}' /proc/mounts 2>/dev/null)
    [ "$fs_type" = tmpfs ] ||         fw_die "$mount_at must be a tmpfs before firmware updating is allowed"
}

valid_sha256() {
    printf '%s' "$1" | grep -Eq '^[0-9a-fA-F]{64}$'
}

verify_sidecar() {
    image=$1
    sidecar=$2
    [ -f "$sidecar" ] || fw_die "checksum sidecar not found: $sidecar"
    hash=$(awk 'NF >= 2 && $1 !~ /^#/ {print tolower($1); exit}' "$sidecar")
    listed=$(awk 'NF >= 2 && $1 !~ /^#/ {$1=""; sub(/^[ \t]+[*]?/, ""); sub(/\r$/, ""); print; exit}' "$sidecar")
    valid_sha256 "$hash" || fw_die "invalid SHA-256 in $sidecar"
    expected_name=$(basename "$image")
    [ "$listed" = "$expected_name" ] || \
        fw_die "checksum filename '$listed' does not match '$expected_name'"
    actual=$(sha256sum "$image" | awk '{print $1}')
    [ "$actual" = "$hash" ] || fw_die "SHA-256 mismatch for $expected_name"
    FWUPDATE_SHA256=$actual
    export FWUPDATE_SHA256
}

verify_expected_hash() {
    image=$1
    expected=$(printf '%s' "$2" | tr 'A-F' 'a-f')
    valid_sha256 "$expected" || fw_die "invalid expected SHA-256"
    actual=$(sha256sum "$image" | awk '{print $1}')
    [ "$actual" = "$expected" ] || fw_die "SHA-256 mismatch for $(basename "$image")"
    FWUPDATE_SHA256=$actual
    export FWUPDATE_SHA256
}

safe_remote_filename() {
    case "$1" in
        ""|*/*|*..*|*[!A-Za-z0-9._-]*) return 1 ;;
        *) return 0 ;;
    esac
}

safe_remote_path() {
    case "$1" in
        ""|*..*|*[!A-Za-z0-9._/-]*) return 1 ;;
        *) return 0 ;;
    esac
}

try_fetch_http_file() {
    url=$1
    out=$2
    rm -f "$out.part"
    case "$url" in
        https://*)
            command -v curl >/dev/null 2>&1 || return 2
            set -- curl --fail --location --show-error --silent \
                --proto '=https' --proto-redir '=https' \
                --retry 3 --connect-timeout 15 --max-time 900
            [ -f /etc/ssl/certs/ca-certificates.crt ] && \
                set -- "$@" --cacert /etc/ssl/certs/ca-certificates.crt
            set -- "$@" --output "$out.part" "$url"
            "$@" || { rm -f "$out.part"; return 1; }
            ;;
        http://*)
            if command -v curl >/dev/null 2>&1; then
                curl --fail --location --show-error --silent \
                    --proto '=http,https' --proto-redir '=http,https' \
                    --retry 3 --connect-timeout 15 --max-time 900 \
                    --output "$out.part" "$url" || { rm -f "$out.part"; return 1; }
            else
                wget -T 30 -t 3 -O "$out.part" "$url" || { rm -f "$out.part"; return 1; }
            fi
            ;;
        *) return 3 ;;
    esac
    mv -f "$out.part" "$out"
}

fetch_http_file() {
    url=$1
    out=$2
    try_fetch_http_file "$url" "$out"
    rc=$?
    [ "$rc" -eq 0 ] && return 0
    case "$rc" in
        2) fw_die "HTTPS requires curl support in the firmware image" ;;
        3) fw_die "unsupported HTTP source URL: $url" ;;
        *) fw_die "download failed: $url" ;;
    esac
}

acquire_lock() {
    if mkdir "$FWUPDATE_LOCK_DIR" 2>/dev/null; then
        echo $$ > "$FWUPDATE_LOCK_DIR/pid"
        return 0
    fi

    owner=$(cat "$FWUPDATE_LOCK_DIR/pid" 2>/dev/null || true)
    [ "$owner" = "$$" ] && return 0
    case "$owner" in
        ''|*[!0-9]*) ;;
        *)
            if kill -0 "$owner" 2>/dev/null; then
                printf 'error: another firmware update appears to be active (pid %s)\n' "$owner" >&2
                exit 1
            fi
            ;;
    esac

    rm -rf "$FWUPDATE_LOCK_DIR" 2>/dev/null || true
    mkdir "$FWUPDATE_LOCK_DIR" 2>/dev/null || {
        printf 'error: another firmware update appears to be active\n' >&2
        exit 1
    }
    echo $$ > "$FWUPDATE_LOCK_DIR/pid"
}

release_lock() {
    owner=$(cat "$FWUPDATE_LOCK_DIR/pid" 2>/dev/null || true)
    if [ -z "$owner" ] || [ "$owner" = "$$" ]; then
        rm -rf "$FWUPDATE_LOCK_DIR" 2>/dev/null || true
    fi
}

cleanup_transport_work() {
    path=${FWUPDATE_TRANSPORT_WORK:-}
    case "$path" in
        "$FWUPDATE_WORK_BASE"/fwupdate-http.*|\
        "$FWUPDATE_WORK_BASE"/fwupdate-tftp.*|\
        "$FWUPDATE_WORK_BASE"/fwupdate-sftp.*)
            rm -rf "$path" 2>/dev/null || true
            ;;
    esac
    FWUPDATE_TRANSPORT_WORK=
    export FWUPDATE_TRANSPORT_WORK
}
