# name|base URL|index filename
# The index format is:
# version|target|firmware filename|byte size|description
#
# Example:
# official|https://firmware.example.net/postmerkos/ms42p|index.tsv
# lab|http://192.168.1.20/firmware/ms42p|index.tsv
