#!/bin/sh
set -eu

: "${TARGET_DIR:?Buildroot TARGET_DIR is not set}"

mkdir -p "$TARGET_DIR/overlay" "$TARGET_DIR/click" "$TARGET_DIR/etc"

# Dropbear host keys are created in the persistent JFFS2-backed /etc overlay.
if [ -L "$TARGET_DIR/etc/dropbear" ]; then
    rm -f "$TARGET_DIR/etc/dropbear"
fi
mkdir -p "$TARGET_DIR/etc/dropbear"

if [ -n "${SOURCE_DATE_EPOCH:-}" ]; then
    image_date="$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y%m%d 2>/dev/null || date -u +%Y%m%d)"
else
    image_date="$(date -u +%Y%m%d)"
fi
release="${MS42P_RELEASE:-$image_date}"

cat > "$TARGET_DIR/etc/lsb-release" <<EOF_RELEASE
DISTRIB_ID="postmerkOS"
DISTRIB_RELEASE="$release"
DISTRIB_DESCRIPTION="postmerkOS MS42P mipsel"
EOF_RELEASE

# S14passwd contains a source-controlled placeholder. Replace it with the salt
# generated by Buildroot for the root account without relying on an unsafe sed
# replacement string.
passwd_script="$TARGET_DIR/etc/init.d/S14passwd"
if [ -f "$passwd_script" ] && grep -qF '__SALT__' "$passwd_script"; then
    salt="$(awk -F: '$1 == "root" { split($2, p, "\\$"); print p[3]; exit }' "$TARGET_DIR/etc/shadow")"
    [ -n "$salt" ] || { echo "Unable to determine root password salt" >&2; exit 1; }
    python3 - "$passwd_script" "$salt" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
path.write_text(path.read_text().replace('__SALT__', sys.argv[2]))
PY
fi

find "$TARGET_DIR/etc/init.d" -maxdepth 1 -type f -exec chmod 0755 {} +
