#!/bin/sh
set -eu

: "${TARGET_DIR:?Buildroot TARGET_DIR is not set}"

mkdir -p "$TARGET_DIR/overlay" "$TARGET_DIR/click" "$TARGET_DIR/etc" "$TARGET_DIR/usr/share/postmerkos"
ln -snf /overlay "$TARGET_DIR/config"

# Dropbear host keys are created in the persistent JFFS2-backed /etc overlay.
if [ -L "$TARGET_DIR/etc/dropbear" ]; then
    rm -f "$TARGET_DIR/etc/dropbear"
fi
mkdir -p "$TARGET_DIR/etc/dropbear"

if [ -n "${SOURCE_DATE_EPOCH:-}" ]; then
    build_version="$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y-%m-%d-%H-%M 2>/dev/null || date -u +%Y-%m-%d-%H-%M)"
else
    build_version="$(date -u +%Y-%m-%d-%H-%M)"
fi
release="${POSTMERKOS_RELEASE:-${MS42P_RELEASE:-$build_version}}"
revision="${POSTMERKOS_GIT_REVISION:-unknown}"
cat > "$TARGET_DIR/etc/postmerkos-release.json" <<EOF_POSTMERKOS_RELEASE
{
  "version": "$release",
  "build_time_utc": "$build_version",
  "git_revision": "$revision",
  "target_family": "vcore3",
  "image_format": 2,
  "config_schema": 3,
  "fwupdate_api": 2,
  "web_api": 2
}
EOF_POSTMERKOS_RELEASE

cat > "$TARGET_DIR/etc/lsb-release" <<EOF_RELEASE
DISTRIB_ID="postmerkOS"
DISTRIB_RELEASE="$release"
DISTRIB_DESCRIPTION="postmerkOS VCore-III mipsel"
EOF_RELEASE

# S14passwd contains a source-controlled placeholder. Replace it with the salt
# generated by Buildroot for the root account without relying on an unsafe sed
# replacement string.
passwd_script="$TARGET_DIR/etc/init.d/S14passwd"
if [ -f "$passwd_script" ] && grep -qF '__SALT__' "$passwd_script"; then
    salt="$(awk -F: '$1 == "root" { split($2, p, "\\$"); print p[3]; exit }' "$TARGET_DIR/etc/shadow")"
    [ -n "$salt" ] || { echo "Unable to determine root password salt" >&2; exit 1; }
    python3 - "$passwd_script" "$salt" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
path.write_text(path.read_text().replace('__SALT__', sys.argv[2]))
PY
fi

find "$TARGET_DIR/etc/init.d" -maxdepth 1 -type f -exec chmod 0755 {} +
