[server]
host-name=postmerkos
domain-name=local
use-ipv4=yes
use-ipv6=no
allow-interfaces=linux_mgmt
enable-dbus=no

[wide-area]
enable-wide-area=no

[publish]
publish-addresses=yes
publish-hinfo=no
publish-workstation=no
publish-domain=no
